name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neovim_version: ['v0.8.0', 'v0.9.0', 'nightly']

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Neovim
      uses: rhymond/setup-neovim@v0.2.0
      with:
        version: ${{ matrix.neovim_version }}
    
    - name: Install dependencies
      run: |
        git clone --depth 1 https://github.com/nvim-lua/plenary.nvim ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim
        git clone --depth 1 https://github.com/ibhagwan/fzf-lua ~/.local/share/nvim/site/pack/vendor/start/fzf-lua
        
    - name: Run tests
      run: |
        nvim --headless -c "PlenaryBustedDirectory tests/ { minimal_init = 'tests/minimal_init.vim' }"