name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neovim_version: ['v0.8.0', 'v0.9.0', 'nightly']

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Neovim
      uses: MunifTanjim/setup-neovim-action@v1
      with:
        tag: ${{ matrix.neovim_version }}
    
    - name: Install dependencies
      run: |
        mkdir -p ~/.local/share/nvim/site/pack/vendor/start
        git clone --depth 1 https://github.com/nvim-lua/plenary.nvim ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim
        git clone --depth 1 https://github.com/ibhagwan/fzf-lua ~/.local/share/nvim/site/pack/vendor/start/fzf-lua
        
    - name: Run tests
      run: |
        nvim --headless -c "PlenaryBustedDirectory tests/ { minimal_init = 'tests/minimal_init.vim' }"